version: "3.9"

volumes:
  portainer_data:

services:
  portainer:
    image: portainer/portainer-ce:2.19.4-alpine # https://hub.docker.com/r/portainer/portainer-ce/tags
    container_name: portainer
    command:
      - "--http-enabled"
      - "--bind=:9000"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.routers.portainer.tls.certresolver=regru"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
