# https://github.com/louislam/uptime-kuma
name: uptime-kuma

networks:
  frontend:
    name: frontend
    external: true

services:
  uptime-kuma:
    # https://hub.docker.com/r/louislam/uptime-kuma/tags
    image: louislam/uptime-kuma:1.23.13-alpine
    container_name: uptime-kuma
#    ports:
#      - 3001:3001
    volumes:
      - /opt/uptime-kuma/data:/app/data
    restart: unless-stopped
    networks:
      - frontend
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - TZ=Europe/Moscow
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.rule=Host(`uptime-kuma.${DOMAIN}`)"
      - "traefik.http.routers.uptime-kuma.entrypoints=websecure"
      - "traefik.http.routers.uptime-kuma.service=uptime-kuma"
      - "traefik.http.routers.uptime-kuma.tls.certresolver=regru"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
