version: "3.9"

volumes:
  ssh:
    external: true

services:
  ssh-tunnel:
    image: "kroniak/ssh-client:3.18"
    container_name: "ssh-tunnel"
    ports:
      - 1080:1080
    restart: unless-stopped
    volumes:
      - ssh:/ssh
    command:
      - "sh"
      - "-c"
      - >
        chmod 700 /ssh/id_rsa && 
        ssh -i /ssh/id_rsa -N -T -D 1080 -4 
        -o StrictHostKeyChecking=no 
        -o GatewayPorts=true 
        -o TCPKeepAlive=no 
        -o ServerAliveCountMax=30 
        -o ServerAliveInterval=30 
        -o ConnectionAttempts=300
        -o ConnectTimeout=30
        -o LogLevel=DEBUG
        ${SSH_TUNNEL_USER}@${SSH_TUNNEL_HOST}
