name: ssh-tunnel
networks:
  frontend:
    name: frontend
    external: true
secrets:
  host_ssh_key:
    file: ~/.ssh/id_rsa
services:
  ssh-tunnel:
    image: "kroniak/ssh-client:3.19"
    container_name: "ssh-tunnel"
    ports:
      - 1080:1080
    restart: unless-stopped
    networks: ["frontend"]
    tty: true
    environment:
      SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
    secrets:
      - host_ssh_key
    command:
      - "sh"
      - "-c"
      - >
        echo $SSH_PRIVATE_KEY | base64 -d > /ssh_private_key &&
        chmod 700 /ssh_private_key &&
        ssh -i /ssh_private_key -N -T -D 1080 -4 
        -o StrictHostKeyChecking=no 
        -o GatewayPorts=true 
        -o TCPKeepAlive=no 
        -o ServerAliveCountMax=30 
        -o ServerAliveInterval=30 
        -o ConnectionAttempts=300
        -o ConnectTimeout=30
        -o LogLevel=DEBUG
        ${SSH_TUNNEL_USER}@${SSH_TUNNEL_HOST}
